### ISSUE TITLE
Reading Template Asset Interfaces Description is not possible

### ISSUE THREAD

**Issue by Christian-Block** [eclipse-aas4j/aas4j#273]
I am currently trying to import the existing IDTA templates. For "Asset Interfaces Description" I use AAS4J in version 1.0.1

However, the following first approach fails.

```
import org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer;
//...
new XmlDeserializer().read(new File("AAS_Template_for_AID.aas.xml"));
```

The XML from the AASX file as *.TXT (due to upload restrictions) is added.

The read method returns this exception:

```
org.eclipse.digitaltwin.aas4j.v3.dataformat.core.DeserializationException: deserialization failed
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:120)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:149)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:168)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:182)
	at eu.eclass.bcon2.aas.v3.V3ImportTest.main(V3ImportTest.java:12)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot invoke "com.fasterxml.jackson.core.TreeNode.isArray()" because "treeNode" is null (through reference chain: org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultEnvironment["submodels"]->java.util.ArrayList[0]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodel["submodelElements"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["value"]->org.eclipse.digitaltwin.aas4j.v3.model.impl.DefaultSubmodelElementCollection["supplementalSemanticIds"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1863)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:83)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:83)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.DeserializationHelper.createInstanceFromNode(DeserializationHelper.java:32)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementDeserializer.deserialize(SubmodelElementDeserializer.java:37)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementFromJsonNode(SubmodelElementsDeserializer.java:103)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.getSubmodelElementsFromObjectNode(SubmodelElementsDeserializer.java:80)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.createSubmodelElements(SubmodelElementsDeserializer.java:61)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:53)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.SubmodelElementsDeserializer.deserialize(SubmodelElementsDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.XmlDeserializer.read(XmlDeserializer.java:118)
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.core.TreeNode.isArray()" because "treeNode" is null
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.ReferencesDeserializer.deserialize(ReferencesDeserializer.java:38)
	at org.eclipse.digitaltwin.aas4j.v3.dataformat.xml.internal.deserialization.ReferencesDeserializer.deserialize(ReferencesDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	... 114 more


```

**Comment by mjacoby** [comment]
The reason is that the XML file is not valid as it contains `<supplementalSemanticIds />` in line 2250, 5205 and 8186 which is not allowed to the [official documentation](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml#optional-properties).
After removing these lines deserialization works find, both from XML and from AASX (after repackaging).

This issue seems very similar to #172 where basically the same thing occurred when trying to deserialize the ContactInformation submodel template. My guess is that this is caused by a bug in AASX Package Explorer which was probably used to create those files. However, I am not going to investigate this further as this is not a bug of AAS4J but rather the case of an invalid input.

I suggest creating an issue in the [repository managing the submodel templates](https://github.com/admin-shell-io/submodel-templates/issues) and request they fix the file.

**Comment by Christian-Block** [comment]
Thank you @mjacoby  for the quick reply.

**Comment by sebastiankb** [comment]
Thank you for pointing this out. The AID Template will be updated.

**Comment by Kaz040** [comment]
As an update, The AID Template has now been updated and passes validation with AAS4J.  Thank you for pointing this out.
